### ISSUE TITLE
add more char name aliases

### ISSUE THREAD

**Issue by Jesse-Heath** [ronoaldo/swgoh#2]
i have the file, but cant push to repo

**Comment by ronoaldo** [comment]
Hi @Jesse-Heath - please fork the repo then open a Pull Request form your feature branch.
More info here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by ronoaldo** [comment]
@Jesse-Heath you can also paste the new names/aliases here and I include them.

**Comment by Jesse-Heath** [comment]
[abilities.go.txt](https://github.com/ronoaldo/swgoh/files/1346304/abilities.go.txt)

**Comment by Jesse-Heath** [comment]
[chars.go.txt](https://github.com/ronoaldo/swgoh/files/1346307/chars.go.txt)

**Comment by ronoaldo** [comment]
Integrated your patched file into the main branch! Thanks for the contribution!
